---
- name: Copy CA certificate
  copy:
    src: "{{ grid_dummy_ca.crt }}"
    dest: /etc/grid-security/certificates/DummyCA.crt

- name: Create link
  file:
    src: DummyCA.crt
    dest: "/etc/grid-security/certificates/{{ grid_dummy_ca.hash }}.0"
    state: link

- name: Generate dummy hostcertificate
  block:

    - name: Copy CA key
      copy:
        src: "{{ grid_dummy_ca.key }}"
        dest: /etc/grid-security/certificates/DummyCA.key
        mode: 0400

    - name: Generate privat key
      command: openssl genrsa -out /etc/grid-security/hostkey.pem 2048
      args:
        creates: /etc/grid-security/hostkey.pem

    - name: Generate certificate request
      command: >
        openssl req -new -sha256
        -key /etc/grid-security/hostkey.pem
        -subj "{{ grid_dummy_ca.cn + ansible_fqdn }}"
        -out /etc/grid-security/hostcert.csr
      args:
        creates: /etc/grid-security/hostcert.csr

    - name: Sign the certificate request
      command: >
        openssl x509 -req -in /etc/grid-security/hostcert.csr
        -CA /etc/grid-security/certificates/DummyCA.crt
        -CAkey /etc/grid-security/certificates/DummyCA.key
        /etc/grid-securiy/hostcert.pem -sha256
      args:
        creates: /etc/grid-securiy/hostcert.pem

  when: grid_enable_dummy_hostcert
