---
- name: Install fetch-crl
  package:
    name: fetch-crl
    state: present

- name: Configure fetch-crl
  template:
    src: fetch-crl.conf.j2
    dest: /etc/fetch-crl.conf

- name: Initial run of fetch-crl
  command: /usr/sbin/fetch-crl
  changed_when: false
  ignore_errors: true

- name: Enable fetch-crl systemd boot service
  service:
    name: fetch-crl-boot
    enabled: true

- name: Enable fetch-crl systemd cron job
  service:
    name: fetch-crl-cron
    enabled: true
    state: started
