---
- name: Install fetch-crl
  package:
    name: fetch-crl
    state: present

- name: Configure fetch-crl
  template:
    src: fetch-crl.conf.j2
    dest: /etc/fetch-crl.conf

# Idempotency: fetch-crl creates the CRL store for the CERN Grid CA (and others).
- name: Initial run of fetch-crl
  command: /usr/sbin/fetch-crl
  args:
    creates: /etc/grid-security/certificates/5168735f.r0
