---
# tasks file for hephyvienna.role-grid
- name: Include OS specific variables
  include_vars: "{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml"

- name: Configure UMD repo
  include_tasks: repos.yml
  when: grid_enable_repo

- name: Install ca_policy
  include_tasks: ca_policy.yml
  when: not grid_cvmfs

- name: Install fetch-crl
  include_tasks: fetch-crl.yml
  when: not grid_cvmfs and grid_install_fetchcrl

- name: Install dummy CA policies
  include_tasks: dummy_ca_policy.yml
  when: grid_cvmfs and grid_install_dummy_ca_policy

- name: Install VOMS
  include_tasks: voms.yml

- name: Install host certificate
  include_tasks: hostcert.yml
  when: grid_host_certificate | length > 0
