---
- name: Converge
  hosts: all
  roles:
    - role: geerlingguy.repo-epel
    - role: hephyvienna.grid
      vars:
        grid_vos:
          - cms
          - alice
          - belle
        grid_enable_dummy_ca: true
        grid_enabel_dummy_hostcert: true
