---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Enable EPEL repository
      package:
        name: epel-release
        state: present

  roles:
    - role: hephyvienna.grid
      vars:
        grid_vos:
          - cms
          - alice
          - belle
        grid_dummy_host_certificate: true
